baseURL = "http://ukstudio.jp"
title = "UKSTUDIO"
author = "AKAMATSU Yuki"
copyright = "AKAMATSU Yuki All rights reserved"
publishDir = 'docs'
theme = 'hugo-zen'
googleAnalytics = "UA-12755601-1"

[params]
  twitter = "https://twitter.com/ukstudio"
  github = "https://github.com/ukstudio"
  logo = '/images/icon.png'
